apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: LoadBalancer
  selector:
    app: java-app-demo  # Ensure this label matches your pod's labels
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
